### ISSUE TITLE
Worse results in segmentation task compared to Figure 4 in paper.

### ISSUE THREAD

**Issue by Harry-Zhi** [yossigandelsman/DoubleDIP#3]
Hi,
I try to use **the provided setup of segmentation** for the bird segmentation task.
Saliency maps are processed by the given "bg_fg_prep.py" before being fed to segmentation.py.

It seems like the generated mask has a very rough estimation of the object boundaries, compared to the sharp and crisp mask in the paper (Figure 4).
![seabird_learned_mask](https://user-images.githubusercontent.com/16745512/63939710-d1148e80-ca5f-11e9-99d7-0a15333ddafd.jpg)
![image](https://user-images.githubusercontent.com/16745512/63939856-2355af80-ca60-11e9-9804-0980cbeeda33.png)

Solider image has worse result and the network cannot separate soldiers and background.

![soldier_learned_mask](https://user-images.githubusercontent.com/16745512/63939945-56983e80-ca60-11e9-8fc9-4ba83c6906f9.jpg)

Could you please tell me what are the potential problems and some advice to improve it? 
Thanks.

**Comment by zhang-lingyun** [comment]
my generated results, also not good as the mask in the paper.
![birds_learned_mask](https://user-images.githubusercontent.com/26016642/69152508-9169ba00-0b17-11ea-9338-49d1e2f0a12d.jpg)
![birds](https://user-images.githubusercontent.com/26016642/69152515-93cc1400-0b17-11ea-93a9-a2cf9e314c9a.jpg).

**Comment by zfy-csu** [comment]
After saliency , the image size will be changed and then the shape of the hint will be different from the origin image.
 Could anybody answer me how to sovle this problem? Thanks very much.

**Comment by zfy-csu** [comment]
After saliency , the image size will be changed and then the shape of the hint will be different from the origin image.
 Could anybody answer me how to sovle this problem? Thanks very much.

**Comment by zfy-csu** [comment]
I resize the image by resize function and my results are still not good enough. I don't know why and how to improve it. Could you give me some advices?
![baby](https://user-images.githubusercontent.com/55080079/96338428-a6045880-10c0-11eb-9c30-f7f45eb98e63.png)
![baby_learned_mask](https://user-images.githubusercontent.com/55080079/96338431-aef52a00-10c0-11eb-95b6-681849b65c99.jpg)
![bird](https://user-images.githubusercontent.com/55080079/96338483-faa7d380-10c0-11eb-9377-705d30e9cc6d.png)
![bird_learned_mask](https://user-images.githubusercontent.com/55080079/96338486-009db480-10c1-11eb-8842-d5700bd62d97.jpg)
![soldier](https://user-images.githubusercontent.com/55080079/96338491-0a271c80-10c1-11eb-90b0-6dcf373b76a0.png)
![soldier_learned_mask](https://user-images.githubusercontent.com/55080079/96338496-114e2a80-10c1-11eb-8e0e-8ac9f4bde59b.jpg)

**Comment by FreyaWan-hub** [comment]
完全复现不出论文里的结果，这作者纯纯乱写的，大家别信，别引用对比这篇工作了
Yossi Gandelsman, shame on u!!!!!!!!
